In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import pandas as pd
df = pd.read_csv('/content/gdrive/MyDrive/Semester_4.1/CSE_404/assignment_2/roadmap_kg_UAP.csv') #reading the csv file
df

                    0                  1     2      3
0         kishoreganj           pakundia  17.1  15.72
1         kishoreganj            katiadi  23.7  20.87
2            pakundia            kapasia  30.8  26.79
3             katiadi          monohardi  16.4  15.13
4             kapasia        rajendrapur  18.1  16.89
5           monohardi           narsindi  28.9  24.46
6         rajendrapur  gazipur chowrasta  12.3  11.21
7            narsindi           kanchpur  43.0  31.00
8            narsindi           madhabdi  10.4   9.34
9   gazipur chowrasta              tongi  17.4  10.15
10           kanchpur         sign board   4.5   4.40
11           madhabdi             bhulta  19.7  13.03
12             bhulta             tarabo  11.2   8.92
13              tongi          mohakhali  17.7  13.38
14         sign board          sayedabad   6.6   6.00
15             tarabo         hatirjheel  16.2  10.94
16          mohakhali                UAP   4.8   0.00
17          sayedabad                UAP   8.2   0.00
18         hatirjheel                UAP   3.7   0.00

In [ ]:
initial_state = 'kishoreganj' #assigning start node
goal = 'UAP' #assigning goal node
kg_hn = 3.59 #assigning the huerestic value of start node kishoreganj
df.columns = [ 'Parent', 'Child', 'g(n)', 'h(n)'] #assigning the headers of the columns
df

               Parent              Child  g(n)   h(n)
0         kishoreganj           pakundia  17.1  15.72
1         kishoreganj            katiadi  23.7  20.87
2            pakundia            kapasia  30.8  26.79
3             katiadi          monohardi  16.4  15.13
4             kapasia        rajendrapur  18.1  16.89
5           monohardi           narsindi  28.9  24.46
6         rajendrapur  gazipur chowrasta  12.3  11.21
7            narsindi           kanchpur  43.0  31.00
8            narsindi           madhabdi  10.4   9.34
9   gazipur chowrasta              tongi  17.4  10.15
10           kanchpur         sign board   4.5   4.40
11           madhabdi             bhulta  19.7  13.03
12             bhulta             tarabo  11.2   8.92
13              tongi          mohakhali  17.7  13.38
14         sign board          sayedabad   6.6   6.00
15             tarabo         hatirjheel  16.2  10.94
16          mohakhali                UAP   4.8   0.00
17          sayedabad                UAP   8.2   0.00
18         hatirjheel                UAP   3.7   0.00

In [ ]:
df['g(n)'] = df['g(n)'].astype('float32') #assigning variable type
df['h(n)'] = df['h(n)'].astype('float32') #assigning variable type
path = [initial_state] #declaring a list
sdf = df.copy() #making a copy 
path_cost = 0 #declaring a variable
while True: #starting a loop
    if initial_state==goal: #checking if found the goal
        break
    sd = sdf[sdf.Parent== initial_state] #putting header value as parent 
    sd['f(n)']=sd[['g(n)','h(n)']].sum(axis=1) #calculating the f(n) value
    
    sd=sd.sort_values(by='f(n)',ascending=True).reset_index(drop=True) #sorting the rows in ascending order
    print(sd) #printing the rows
    initial_state = sd.loc[0].Child #setting the new header
    path_cost+=sd.loc[0]['g(n)']#.value #calculating the path cost
    path_cost+=sd.loc[0]['h(n)']
    path.append(initial_state) #putting the new header into the list

        Parent     Child       g(n)       h(n)   f(n)
0  kishoreganj  pakundia  17.100000  15.720000  32.82
1  kishoreganj   katiadi  23.700001  20.870001  44.57
     Parent    Child       g(n)       h(n)   f(n)
0  pakundia  kapasia  30.799999  26.790001  57.59
    Parent        Child  g(n)       h(n)       f(n)
0  kapasia  rajendrapur  18.1  16.889999  34.989998
        Parent              Child  g(n)   h(n)   f(n)
0  rajendrapur  gazipur chowrasta  12.3  11.21  23.51
              Parent  Child  g(n)   h(n)       f(n)
0  gazipur chowrasta  tongi  17.4  10.15  27.549999
  Parent      Child       g(n)   h(n)       f(n)
0  tongi  mohakhali  17.700001  13.38  31.080002
      Parent Child  g(n)  h(n)  f(n)
0  mohakhali   UAP   4.8   0.0   4.8

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [ ]:
print('Optimal path ',path) #printing the optimal path
print('Optimal path cost is ',kg_hn+path_cost,'km') #printing the path cost

Optimal path  ['kishoreganj', 'pakundia', 'kapasia', 'rajendrapur', 'gazipur chowrasta', 'tongi', 'mohakhali', 'UAP']
Optimal path cost is  215.9300011062622 km